### PR TITLE
Additional features

### PR DESCRIPTION
**Pull request by matteodem**

### CODE REVIEW

**Comment by ramon82** [comment]
Thank you @matteodem! I'm gonna review your code and merge with a new version with some other bugs fixed asap

**Comment by matteodem** [comment]
No problem! 

Please don't merge yet though, it's still a WIP. Let me know if you have any day that you want this new version to be released on. I'll try to get it finished by then

**Comment by matteodem** [comment]
Also I made the changes in the root zuck.js because I don't know what transpilation process you have.

Maybe you can clone the changes into the src/zuck.js and just tag me in the commit? :) Or I'll add the changes to the other file too and then do the transpilation

**Comment by ramon82** [comment]
I'm not having much time to update the script now and I think the last version is broken, so I must fix some other things too... is it ok if I tag you in a commit with those things together on the next version?

**Comment by matteodem** [comment]
sure, sounds good!

**Comment by ramon82** [comment]
Added to new version

**Pull request closed without merging**
